name: Sync with Upstream

on:
  schedule:
    - cron: '0 3 * * *'  # every day at 3 AM UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork
        uses: tgymnich/fork-sync@v1.8
        with:
          owner: ExtremeXT
          repo: M62-backport
          base: main
          head: main
          token: ${{ secrets.GITHUB_TOKEN }}
