name: Clone M62-backport into branch

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
  workflow_dispatch:

jobs:
  clone-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout m62-backport branch
        uses: actions/checkout@v4
        with:
          ref: m62-backport
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove existing files (except .git and workflows)
        run: |
          shopt -s extglob
          rm -rf !(.git|.github)

      - name: Clone upstream repo into temporary folder
        run: |
          gh repo clone ExtremeXT/M62-backport temp-upstream

      - name: Copy upstream files into branch
        run: |
          cp -r temp-upstream/* .
          rm -rf temp-upstream

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Daily sync: Clone of ExtremeXT/M62-backport"
          git push origin m62-backport
        continue-on-error: true
